### PR TITLE
Return asset content type in response of record save

### PR DESCRIPTION
**Pull request by b123400**
connect #327 

This PR makes sure asset's information is complete, but [it is not perfect](https://github.com/SkygearIO/skygear-server/issues/327#issuecomment-288522101)

### CODE REVIEW

**Comment by oursky-travis** [comment]
@b123400, thanks for your PR! By analyzing the history of the files in this pull request, we identified @cheungpat, @limouren and @rickmak to be potential reviewers.

**Comment by b123400** [comment]
Updated to inject signer after querying asset.

Not sure if it's golang issue or our problem, but the current structure make things super easy to be invalid. If I want to query a record, I have to remember to inject the assets, and then inject the signer, forget anyone them will give no warning at all.

**Comment by rickmak** [comment]
There should be an runtime error `log.Warnf("Unable to generate signed url of asset because no singer is injected.")`, refs: https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skydb/record.go#L196

Or you want an exception? Reason is?

**Comment by rickmak** [comment]
Or you are expecting compiling error?

**Pull request merged**
