### PR TITLE
next: Add migration to gateway with Makefile

### PR DESCRIPTION
**Pull request by rickmak**
connect #624

### CODE REVIEW

**Comment by Steven-Chan** [comment]
I think `WITH_DOCKER` is better than `NO_DOCKER` https://github.com/SkygearIO/skygear-server/blob/master/Makefile#L28, but as long as the option is there, i am fine.

**Comment by rickmak** [comment]
WITH_DOCKER=0 or NO_DOCKER=1 that is the question. Wording itself is telling with is default IMO.

**Comment by Steven-Chan** [comment]
The difference is `WITH_DOCKER` in the skygear-server example does not alter the cmd, but prepend docker cmd.

**Comment by rickmak** [comment]
Seem it is not possible with the migrate/migrate docker image? I did not check details. @carmenlau ?

**Comment by carmenlau** [comment]
`migrate/migrate` docker image itself is an executable with entry point calling the binary, so the command will be a bit different between with or without docker. So cannot simply prepend docker cmd, the binary path are different.

I think using docker should be the default? As I think in most of the case we don't want install extra command? :P 

How about change to `WITH_DOCKER` and `WITH_DOCKER ?= 1`? If it looks good, let me change it :)

**Comment by Steven-Chan** [comment]
@carmenlau Then i'm ok with `NO_DOCKER`.

**Comment by carmenlau** [comment]
Cool, let use Rick's commit. I picked rick's commit to my PR and did some small update for the schema in the PR. Let's continue there.

**Pull request closed without merging**
