### PR TITLE
Fix handler error handling

### PR DESCRIPTION
**Pull request by kiootic**
ref #1040

### CODE REVIEW

**Comment by kiootic** [comment]
For example, when database is down, `Transactional` would panic with a 'connection refused' error. The deferred block would then run and, while `result` and `err` is nil, panic again in `WriteResponse`.

**Comment by louischan-oursky** [comment]
Do you think we should reduce the usage of `panic` in our code? `panic` can still be used in cases like exhaustive switch statement or unreachable code.

**Comment by kiootic** [comment]
I agree. However, we still need to handle when there is unexpected panic.

**Comment by louischan-oursky** [comment]
I think we have a recover middleware for that?

**Comment by kiootic** [comment]
The problem is we're doing response writing in a deferred block, which run regardless of panic. The `WriteResponse` function would panic itself if the panic is not handling correctly.

**Comment by louischan-oursky** [comment]
Per our offline discussion, we are going to refactor the code so that the defer block will be gone.

**Pull request merged**
