### PR TITLE
Send JSON-encoded plugin call in http request body

### PR DESCRIPTION
**Pull request by cheungpat**
connects skygeario/py-skygear#82

### CODE REVIEW

**Comment by oursky-travis** [comment]
@cheungpat, thanks for your PR! By analyzing the annotation information on this pull request, we identified @rickmak to be a potential reviewer

**Comment by cheungpat** [comment]
@ben181231 please see if this PR will cause conflict to your side

**Comment by ben181231** [comment]
@cheungpat Seems fine. Just a little bit conflict. Can be resolved.
Will you also refactor the `exec` transport to use `plugin/request` ?
On my side, I will remove `RunInit()` and merge it as an event.

**Comment by cheungpat** [comment]
> Will you also refactor the exec transport to use plugin/request ?

no

**Comment by ben181231** [comment]
Picked as 0982212

**Pull request closed without merging**
