### PR TITLE
Allow plugin to send request to server

### PR DESCRIPTION
**Pull request by b123400**
connect https://github.com/SkygearIO/skygear-server/issues/304

### CODE REVIEW

**Comment by rickmak** [comment]
May you rebase it?

**Comment by b123400** [comment]
Rebased

**Comment by rickmak** [comment]
Looks good to me, waiting https://github.com/SkygearIO/py-skygear/pull/126

**Comment by rickmak** [comment]
btw, please add test case to both PR.

**Comment by b123400** [comment]
Added test case

**Pull request merged**
