### PR TITLE
Implement GeoJSON query using ST_Contains

### PR DESCRIPTION
**Pull request by cheungpat**
I am creating this WIP PR to request for comment. The pull request has some test case and I expect them to pass, but I don’t have much confidence in the quality of the code at the moment. Rather than me vetting the code for longer, I would like to have comments for specific parts to improve since I have already spent too much time then expected.

@rickmak @lampercy please comment. thanks.

connects #262

### CODE REVIEW

**Comment by cheungpat** [comment]
please review @rickmak

**Comment by rickmak** [comment]
We need to modify the the `handler/query.go` for parsing the query?

I try this predicate and it fails to parse at parser:

```
[
     "in",
     {
       "$type": "geojson",
       "$val": {
         "type": "Point", 
         "coordinates": [102.0, 0.5]
       }
     },
     {
       "$type": "keypath",
       "$val": "geojson"
     }
]
```

I will continue to review tomorrow.... need sometime to load the model back to my mind.

**Comment by cheungpat** [comment]
> We need to modify the the handler/query.go for parsing the query?

Yes. Missed that part.

**Comment by cheungpat** [comment]
The new commits should fix the problem.

**Pull request merged**
