### PR TITLE
Create master user when master key is provided

### PR DESCRIPTION
**Pull request by b123400**
connect #261 

Ready for review~

### CODE REVIEW

**Comment by rickmak** [comment]
I remember someone want this:
> every usernames are equal just like everyone is equal

So a better solution can be: `asUserID` is `_god` at plugin runtime by default. i.e. If the `skygear-node` or `py-skygear` runtime supply `_god` as `asUserID` attribute if it is not supplied by the developer. Of course in cloud deployment it will always set to `_god`.

So in skygear-server, the logic will become `create a user if not exists when accessing with masterkey`

Though?

**Comment by b123400** [comment]
Oh I made it partially similar to your suggestion.

- If master key is used and no user is supplied, a `_god` user is create on the server side.
- The created user has `_id = _god` and empty username

**Comment by rickmak** [comment]
Yes. I know.

My question is are you willing to remove the hard code here and put it in `plugin`. Do you thinks it is more beautiful? And API wise more versatile.

**Comment by b123400** [comment]
I think implicit user creation should be avoided. We are doing this because we need a user to fill in the `created_by` `updated_by` columns, it is an internal process, that I hope the plugin wouldn't need to know.

If we allow plugins to create new users via `asUserID`, we will have implicit user creation which I think is confusing, and not useful. If developer wants an account, they should register, not specifying a unused id in `asUserID`

**Comment by rickmak** [comment]
> If developer wants an account, they should register

This is exactly what issue #261 telling us the user don't want to register an account. They just want their record being saved and associated with the device/user.

As far as I know, #261 is coming from IoT request. It will be really glad if @david90 can provide a use-case for discussion.

**Comment by ben181231** [comment]
> If we allow plugins to create new users via `asUserID`, we will have implicit user creation which I think is confusing, and not useful.

I don't like implicit user creation either. That seems quite confusing to users, unless we have enough documentation to emphasize it. But I cannot think of a better solution than that and it fits IoT use cases a lot.

**Comment by b123400** [comment]
Ok, I will create user implicitly

**Pull request closed without merging**
