### PR TITLE
Implement `user:me` endpoint to get current user

### PR DESCRIPTION
**Pull request by ben181231**
connect #111

### CODE REVIEW

**Comment by ben181231** [comment]
@rickmak The PR is updated.

**Comment by cheungpat** [comment]
@ben181231 you need to rebase this pull request

**Comment by ben181231** [comment]
Okay. 😓

**Comment by ben181231** [comment]
Close it first. Will submit another PR after rebase.

**Comment by ben181231** [comment]
Rebased PR: #116

**Pull request closed without merging**
